pipeline {
    agent any

    stages {
        stage('Build Production') {
            steps {
                dir('devtool_homework_week10/build-production') { // change directory to Lab_docker_Jenkins
                    echo "Current path is ${pwd()}"
                    echo "Create Container of docker-compose"
                    sh "docker-compose up -d"
                }
            }
        }
    }
}




