// pipeline {
//     agent any
//     stages {
//         stage('Sent to Slaves to Build') {
//             steps {
//                 node('slave'){
//                     echo "Current path is ${pwd()}"
//                     echo "Create Container of docker-compose"
//                     // sh "docker-compose up -d"
//                 }
//             }
//         }
//     }
// }



                node('slave'){
                    stage('Sent to Slaves to Build') {
            steps {
                    echo "Current path is ${pwd()}"
                    echo "Create Container of docker-compose"
                    sh "docker-compose up -d"
            }
                }
                }
