pipeline {
    agent any

    stages {
        stage('Sent to Slaves to Build') {
            steps {
                node('slave') {
                    stage('Building') {
                        dir('devtool_homework_week10/build-production') { 
                            echo "Current path is ${pwd()}"
                            echo "Create Container of docker-compose"
                            sh "docker-compose up -d"
                        }
                    }
                }
            }
        }
    }
}
